---
title: ""
author: "Kirsten Gotting"
directory: "`r getwd()`"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: cerulean
    code_folding: hide
    code_download: TRUE
    
---

```{r setup, message=FALSE, results = 'hide', warning=FALSE, error = FALSE}

library(knitr)
opts_chunk$set(message=FALSE, results = 'hide', fig.keep="all", warning=FALSE, error=FALSE, fig.path="./analysis_figures/")

library(wesanderson)
##library(seqinr)
library(pheatmap)
library(tidyverse)

my_pallete <- c(wes_palettes$Rushmore[-2], wes_palettes$FantasticFox)
##Working Directory:`r getwd()`

```




## Overview



## Data Sources


## Analysis


## Results

```{r, results="asis", eval = FALSE, echo = FALSE}

pander::pandoc.table()

``` 

```{r, results='asis', eval = FALSE, echo = FALSE}

DT::datatable(extensions = c('Buttons', 'FixedHeader', 'Scroller'), options = list(
    dom = 'frtBip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    deferRender = TRUE,
    scrollY = 200,
    scroller = TRUE)
    )

```

## Commands Used {.tabset}

```{r, engine='sh', echo = TRUE, results='markup', eval = FALSE}

```




```{r sessionInfo, echo=FALSE}
dir.create('sessionInfo')
writeLines(capture.output(sessionInfo()), "sessionInfo/sessionInfo1.txt")
```

#[R-session information](`r paste0("/sessionInfo/sessionInfo1.txt")`)


